pdf_maneger:
  pdf_path: 'main\components\menu_maneger\pdf_dir\menu_image_2.jpg'
  pdf_dir: main/components/menu_maneger/pdf_dir
  extracted_menu_dir: main/components/menu_maneger/extracted_menu_dir
  final_json_file_name: 'reviewed_menu_data.json'
  extracter_model_name: 'llama-3.3-70b-versatile'

local_models:
  speech_recog_model: models/speech_recog_model
  speech_to_text_model: 'base'

cashier:
  base_model_path: models/base_model
  base_model_id: 'google/gemma-3-4b-it'
  # base_model_id: 'google/gemma-3-1b-it'
  # base_model_id: 'meta-llama/Llama-3.2-1B'
  # base_model_id: 'meta-llama/Llama-3.1-8B-Instruct'

artifacts:
  datasets: artifacts/datasets
  raw_datasets: artifacts/raw_datasets

intent_recog:
  nltk_path: nltk_data