pdf_maneger:
  pdf_path: 'main\components\menu_maneger\pdf_dir\3_zom_cafe.png'
  pdf_dir: main/components/menu_maneger/pdf_dir
  extracted_menu_dir: main/components/menu_maneger/extracted_menu_dir
  json_file_name: 'reviewed_menu_data.json'
  final_json_file_name: 'manual_reviewed_menu_data.json'
  extracter_model_name: 'llama-3.3-70b-versatile'

local_models:
  speech_recog_model: models/speech_recog_model
  speech_to_text_model: 'base'

cashier:
  base_model_path: models/base_model
  base_model_id: 'google/gemma-3-4b-it'
  # base_model_id: 'google/gemma-3-1b-it'
  # base_model_id: 'meta-llama/Llama-3.2-1B'
  # base_model_id: 'meta-llama/Llama-3.1-8B-Instruct'
  fine_tuned_model: 'models/Qwen2.5-0.5B-v2.2-finetunned-Instruct-merged'
  rag_file_in_json: 'main\components\menu_maneger\extracted_menu_dir\test.jsonl'

artifacts:
  datasets: artifacts/datasets
  raw_datasets: artifacts/raw_datasets

intent_recog:
  nltk_path: nltk_data

chat_history:
  chat_history_path: history
  chat_history_file_name: chat_history.json