pdf_maneger:
  pdf_path: 'main\components\menu_maneger\The_Taj_Mahal_Palace_menu.pdf'
  pdf_dir: main/components/menu_maneger/pdf_dir

local_models:
  speech_recog_model: models/speech_recog_model
  speech_to_text_model: 'base'

cashier:
  base_model_path: models/base_model
  base_model_id: 'google/gemma-3-1b-it'
  # base_model_id: 'meta-llama/Llama-3.2-1B'
  # base_model_id: 'meta-llama/Llama-3.1-8B-Instruct'